id: I77B27726
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T12:03:41+00:00'
last_modified: '2022-06-08T10:09:02.169916+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19191
  title: 'ལེགས་པར་བཤད་པ་རིན་པོ་ཆེའི་གཏེར།

    '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D69E:
      image_group_id: I2PD19336
      title: ''
      total_pages: 214
      order: 1
      base_file: D69E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
