id: P009316
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19191
  title: 'ལེགས་པར་བཤད་པ་རིན་པོ་ཆེའི་གཏེར།

    '
  author: ''
  volumes:
    5bab10034aa2424799de870e24117ac4:
      image_group_id: I2PD19336
      title: ''
      volume_number: 1
      total_pages: 214
      base_file: v001.txt
